// DocX documentation generator. Scrapes prose @doc tags from ANY text file
// (source, HTML comments, config) — no grammar needed, since docs only need the
// tags, not code structure. Emits a single Markdown guide with a Mermaid
// architecture diagram, regenerated from source so it can never go stale.
import * as fs from "fs";
import * as path from "path";
import { parseKv } from "../core/tags";
import { loadScope, inScope, walkFiles } from "../scope";

const SCAN_EXT = new Set([
  ".py", ".js", ".mjs", ".cjs", ".jsx", ".ts", ".tsx", ".go", ".rs", ".rb",
  ".php", ".pl", ".pm", ".html", ".htm", ".vue", ".svelte", ".css", ".md", ".sql",
]);
const TAG = /@(doc[a-z]+)\s*:\s*(.*?)\s*(?:-->|\*\/)?\s*$/;
const isDocFile = (f: string) => SCAN_EXT.has(path.extname(f).toLowerCase()) || path.basename(f) === "Caddyfile";

export interface Entry { token: string; kv: Record<string, any>; raw: string; file: string; line: number; }

export function scan(root: string): Entry[] {
  const out: Entry[] = [];
  const scope = loadScope(root);
  for (const full of walkFiles(root, isDocFile)) {
    if (!inScope(path.relative(root, full), scope)) continue;
    fs.readFileSync(full, "utf8").split(/\r?\n/).forEach((ln, i) => {
      const m = ln.match(TAG);
      if (m) out.push({ token: m[1], kv: parseKv(m[2]), raw: m[2].trim(), file: path.relative(root, full), line: i + 1 });
    });
  }
  return out;
}

const sid = (s: string) => s.replace(/[^A-Za-z0-9_]/g, "_");
const ref = (e: Entry) => `\`${e.file}:${e.line}\``;

function mermaid(archs: Entry[]): string {
  if (!archs.length) return "";
  const edges: string[] = [];
  const nodes = new Map<string, string>();
  for (const e of archs) {
    const comp = e.kv.component || e.kv.name;
    if (!comp) continue;
    nodes.set(sid(comp), comp);
    const rel = e.kv.relies_on || e.kv.depends_on;
    for (const dep of Array.isArray(rel) ? rel : rel ? [rel] : []) {
      nodes.set(sid(dep), dep);
      edges.push(`  ${sid(comp)} --> ${sid(dep)}`);
    }
  }
  const nodeLines = [...nodes].map(([id, label]) => `  ${id}["${label}"]`);
  return "```mermaid\nflowchart LR\n" + nodeLines.join("\n") + (edges.length ? "\n" + edges.join("\n") : "") + "\n```\n";
}

function section(title: string, tokens: string[], entries: Entry[], describe: (e: Entry) => string): string {
  const hits = entries.filter((e) => tokens.includes(e.token));
  if (!hits.length) return "";
  const lines = hits.map((e) => `- ${describe(e)} — ${ref(e)}`);
  return `\n## ${title}\n\n${lines.join("\n")}\n`;
}

const kvStr = (kv: Record<string, any>, keys: string[]) =>
  keys.filter((k) => kv[k] !== undefined).map((k) => `**${k}**: ${Array.isArray(kv[k]) ? kv[k].join(", ") : kv[k]}`).join(", ");

export interface Bridge { from: string; to: string; file: string; line: number }

function sequenceDiagram(bridges: Bridge[]): string {
  if (!bridges.length) return "";
  const parts = new Map<string, string>();
  const edges: string[] = [];
  for (const b of bridges) {
    const a = sid(b.from), z = sid(b.to);
    parts.set(a, b.from); parts.set(z, b.to);
    edges.push(`  ${a}->>${z}: hop`);
  }
  const decl = [...parts].map(([id, label]) => `  participant ${id} as ${label}`);
  return "```mermaid\nsequenceDiagram\n" + decl.join("\n") + "\n" + edges.join("\n") + "\n```\n";
}

export function render(entries: Entry[], bridges: Bridge[] = []): string {
  const archs = entries.filter((e) => e.token === "docarch");
  const now = new Date().toISOString().slice(0, 10);
  let md = `# Project Documentation\n\n> Generated by \`docx-pi docs\` on ${now} from DocX annotations. ` +
    `Do not edit by hand — re-run the generator. ${entries.length} annotation(s) across the codebase.\n`;

  if (archs.length) {
    md += `\n## Architecture\n\n${mermaid(archs)}\n### Components\n\n`;
    md += archs.map((e) => {
      const comp = e.kv.component || e.kv.name || "(unnamed)";
      const extra = kvStr(e.kv, ["layer", "relies_on", "depends_on"]);
      return `- **${comp}**${extra ? " — " + extra : ""} — ${ref(e)}`;
    }).join("\n") + "\n";
  }

  md += section("Business & Intent", ["docbiz", "docspec"], entries, (e) => kvStr(e.kv, ["intent", "given", "when", "then", "value"]) || JSON.stringify(e.kv));
  md += section("Security & Compliance", ["docrisk", "doccomp", "docperm", "doctaint", "docpriv"], entries, (e) => `\`${e.token}\` ${kvStr(e.kv, ["standard", "section", "boundary", "vector", "role_required", "auth", "classification", "source", "status", "masking"]) || JSON.stringify(e.kv)}`);
  md += section("Operations & Runbooks", ["docrun", "docfail", "docmet", "docenv"], entries, (e) => `\`${e.token}\` ${kvStr(e.kv, ["triage", "fallback", "alert", "latency_budget_ms", "max_memory_mb", "platform", "runtime"]) || JSON.stringify(e.kv)}`);
  md += section("Data & Interface", ["docdata", "docux"], entries, (e) => `\`${e.token}\` ${kvStr(e.kv, ["origin", "sink", "component", "wcag", "layout"]) || JSON.stringify(e.kv)}`);
  md += section("Change Log", ["docchg"], entries, (e) => kvStr(e.kv, ["deprecated_since", "removal", "removal_target", "migrate_to"]) || JSON.stringify(e.kv));
  md += section("Interfaces", ["docstring"], entries, (e) => kvStr(e.kv, ["lifecycle", "stability", "validation_state", "audit_trail"]) || e.raw);
  md += section("Invariants & Contracts", ["docinv"], entries, (e) => `\`${e.raw}\``);
  md += section("Subtyping (Liskov)", ["docsub"], entries, (e) => kvStr(e.kv, ["mode", "target", "override", "override_method"]) || e.raw);
  md += section("Configuration", ["doccfg", "docenv"], entries, (e) => `\`${e.token}\` ${kvStr(e.kv, ["log_level", "retry_max", "platform", "runtime", "memory_limit_mb"]) || e.raw}`);
  md += section("Developer Setup", ["docdev"], entries, (e) => kvStr(e.kv, ["bootstrap", "mock", "engine_mock"]) || e.raw);
  md += section("Test Fixtures", ["docmock"], entries, (e) => e.raw);
  md += section("Cost Budgets", ["doccost"], entries, (e) => kvStr(e.kv, ["max_spend_per_million_calls", "max_compute_spend_per_million_calls"]) || e.raw);
  md += section("Policy Exceptions", ["docrule"], entries, (e) => kvStr(e.kv, ["exception", "reason", "suppress", "code_density", "optimization"]) || e.raw);

  const seq = sequenceDiagram(bridges);
  if (seq) md += `\n## Runtime Sequence (from doctrace)\n\n${seq}`;

  const shown = new Set(["docarch", "docbiz", "docspec", "docrisk", "doccomp", "docperm", "doctaint", "docpriv", "docrun", "docfail", "docmet", "docenv", "docdata", "docux", "docchg", "docinv", "docstring", "docsub", "doccfg", "docdev", "docmock", "doccost", "docrule"]);
  if (!entries.some((e) => shown.has(e.token)) && !bridges.length) {
    md += `\n_No prose annotations found. Add tags like \`@docarch: component = "X"\` to build this guide._\n`;
  }
  return md;
}

// doctrace: both structured (@doctrace: from = "A", to = "B") and the [BRIDGE: A -> B] marker.
export function scanBridges(root: string, entries: Entry[]): Bridge[] {
  const out: Bridge[] = [];
  for (const e of entries) {
    if (e.token === "doctrace" && e.kv.from && e.kv.to) out.push({ from: String(e.kv.from), to: String(e.kv.to), file: e.file, line: e.line });
  }
  const scope = loadScope(root);
  for (const full of walkFiles(root, isDocFile)) {
    if (!inScope(path.relative(root, full), scope)) continue;
    fs.readFileSync(full, "utf8").split(/\r?\n/).forEach((line, i) => {
      const m = line.match(/\[BRIDGE:\s*(.+?)\s*->\s*(.+?)\]/);
      if (m) out.push({ from: m[1].trim(), to: m[2].trim(), file: path.relative(root, full), line: i + 1 });
    });
  }
  return out;
}

export function generateDocs(root: string): { markdown: string; count: number } {
  const entries = scan(root);
  const bridges = scanBridges(root, entries);
  return { markdown: render(entries, bridges), count: entries.length };
}
